/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

import org.teavm.gradle.api.JSModuleType

plugins {
  id("java")
  alias(libs.plugins.teavm)
}

repositories {
  mavenCentral()
}

dependencies {
  implementation(libs.pgpainless.core) {
    exclude(group = "org.slf4j", module = "slf4j-api")
  }
  teavm(teavm.libs.jsoApis)
}

teavm.js {
  mainClass = "com.github.renovatebot.Main"
  // addedToWebApp = false
  moduleType = JSModuleType.ES2015
  obfuscated = false
  outputDir = file("dist")
  relativePathInOutputDir = ""
  outOfProcess = true
}


tasks.named("build") { finalizedBy("generateJavaScript") }
