/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

import org.teavm.gradle.api.JSModuleType

plugins {
  id("java-common-conventions")
  war
  alias(libs.plugins.teavm)
  id("org.gretty") version "4.1.10"
}

dependencies {
  implementation(libs.bouncycastle.bcpg)
  implementation(project(":tools:teavm-plugin"))
  teavm(teavm.libs.jsoApis)
}


teavm.wasmGC {
  addedToWebApp = true
  mainClass = "com.github.renovatebot.Test"
  // outputDir = file("..")
  // relativePathInOutputDir = "dist"

  importedWasmMemory = true
  strict = true
  // disassembly = true
  obfuscated = false
  modularRuntime = true
  // debugInformation = true
  // outOfProcess = true
  // sourceMap = true
}


// tasks.assemble.configure {
//   dependsOn(tasks.buildWasmGC)
// }

gretty {
  extraResourceBase("build/generated/teavm")
}
