/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

import org.teavm.gradle.api.JSModuleType

plugins {
  id("java-common-conventions")
  alias(libs.plugins.teavm)
}

dependencies {
  implementation(libs.bouncycastle.bcpg)
  implementation(project(":tools:teavm-plugin"))
  teavm(teavm.libs.jsoApis)
}

teavm.js {
  mainClass = "com.github.renovatebot.Main"
  // addedToWebApp = false
  moduleType = JSModuleType.ES2015
  obfuscated = true
  outputDir = file("../dist")
  relativePathInOutputDir = "teavm"
  // outOfProcess = true
  // sourceMap = true
}

teavm.wasmGC {
  mainClass = "com.github.renovatebot.Main"
  outputDir = file("../dist")
  relativePathInOutputDir = "teavm"
  strict = true
  // disassembly = true
  obfuscated = false
  modularRuntime = true
  // debugInformation = true
  // outOfProcess = true
  // sourceMap = true
}


tasks.assemble.configure {
  dependsOn(tasks.generateJavaScript)
  dependsOn(tasks.buildWasmGC)
}
