/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

import org.teavm.gradle.api.JSModuleType

plugins {
  `java`
  alias(libs.plugins.teavm)
}

dependencies {
  implementation(libs.bouncycastle.bcpg)
  implementation(project(":tools:teavm-plugin"))
  teavm(teavm.libs.jsoApis)
}

teavm.js {
  mainClass = "com.github.renovatebot.Main"
  // addedToWebApp = false
  moduleType = JSModuleType.ES2015
  obfuscated = true
  outputDir = file("../dist")
  relativePathInOutputDir = ""
  // outOfProcess = true
  // sourceMap = true
}

teavm.wasi {
  mainClass = "com.github.renovatebot.Main"
  outputDir = file("../dist")
  relativePathInOutputDir = ""
  // outOfProcess = true
  // sourceMap = true
}

teavm.wasm {
  mainClass = "com.github.renovatebot.Main"
  outputDir = file("../dist")
  relativePathInOutputDir = ""
  // outOfProcess = true
  // sourceMap = true
}

teavm.wasmGC {
  mainClass = "com.github.renovatebot.Main"
  outputDir = file("../dist")
  relativePathInOutputDir = "wasm"
  // outOfProcess = true
  // sourceMap = true
}


tasks.named("build") {
  finalizedBy("generateJavaScript")
  // finalizedBy("buildWasmGC")
}
